runtime: custom
env: flex

# Optional: Add service name, scaling, and resource settings as needed.
# Example:
# service: social-game-backend
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10

# Ensure App Engine uses the PORT environment variable your app listens on.
# The Dockerfile EXPOSEs 8080, and server2/src/config.ts uses process.env.PORT || 3000.
# App Engine will set PORT to 8080 by default for custom runtimes.
